[postgres-edge]
description = "Smoke edge backup to S3"
conninfo = host=postgres user=barman dbname=postgres
streaming_conninfo = host=postgres user=streaming_barman dbname=postgres
backup_method = postgres
streaming_archiver = on
slot_name = barman_edge
create_slot = auto
basebackups_directory = s3://pg-backup-smoke
wals_directory = s3://pg-backup-smoke
backup_directory = /var/lib/barman/postgres-edge
xlogdb_directory = /var/lib/barman/postgres-edge/xlogdb
cloud_staging_directory = /var/lib/barman/cloud-staging
cloud_staging_max_size = 1Gi
minimum_redundancy = 0
retention_policy = RECOVERY WINDOW OF 7 DAYS
