services:
  postgres:
    image: postgres:17
    container_name: postgres
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
      - ./pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
      - ./postgresql.conf:/var/lib/postgresql/data/postgresql.conf

