[postgres-offsite]
description = "Smoke offsite backup to local storage"
conninfo = host=postgres user=barman dbname=postgres
streaming_conninfo = host=postgres user=streaming_barman dbname=postgres
backup_method = postgres
streaming_archiver = on
slot_name = barman_offsite
create_slot = auto
minimum_redundancy = 0
retention_policy = RECOVERY WINDOW OF 7 DAYS
