#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE ROLE barman WITH LOGIN SUPERUSER PASSWORD '${BARMAN_PASSWORD}';
    CREATE ROLE streaming_barman WITH LOGIN REPLICATION PASSWORD '${STREAMING_BARMAN_PASSWORD}';
EOSQL
